{
 "title": "Stacks",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Satoshi remaining",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(50000000 - (stacks_node_btc_ops_sent_total * 20000))"
    }
   ]
  },
  {
   "title": "BTC spend",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stacks_node_btc_ops_sent_total * 1.6"
    }
   ]
  },
  {
   "title": "Blocks mined total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stacks_node_stx_blocks_mined_total"
    }
   ]
  },
  {
   "title": "BTC commits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "stacks_node_btc_ops_sent_total" }
   ]
  },
  {
   "title": "Current profit",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(stacks_node_stx_blocks_mined_total * 500 * 0.11) - (stacks_node_btc_ops_sent_total * 1.6)"
    }
   ]
  },
  {
   "title": "STX won",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stacks_node_stx_blocks_mined_total * 500 * 0.11"
    }
   ]
  },
  {
   "title": "Blocks mined rate (1h)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(stacks_node_stx_blocks_mined_total[1h])"
    }
   ]
  },
  {
   "title": "Active Miners",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stacks_node_active_miners_total"
    }
   ]
  }
 ]
}